name: sasmine
description: SASMINE is an application for mining operations.

publish_to: 'none'
version: 1.0.5


# slidy generate widgets modules/sensor/widgets/ automatiza o caminho para geração de widgets
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  intl: ^0.17.0
  path_provider: ^2.0.11

 
# overrides de dependências só funcinada em modo dev
# quando gerado apk release as dependências não são sobreposta
# por isso é somente indicado para dependências de desenvolvimento
#dependency_overrides:



 
